crate::chart_config!(HeatmapConfig, 720, 0;
    struct {
        pub variant: super::variant::HeatmapVariant,
        pub row_labels: &'a [String],
        pub col_labels: &'a [String],
        pub flat_matrix: &'a [f64],
        pub show_values: bool,
        pub value_min_cell: i32,
        pub value_decimals: usize,
        pub col_label_angle: i32,
        pub color_low: u32,
        pub color_mid: u32,
        pub color_high: u32,
        pub palette: &'a [u32],
        pub discrete_steps: usize,
        pub log_scale: bool,
        pub diverging: bool,
        pub x_widths: &'a [f64],
        pub y_heights: &'a [f64],
        pub annotate: bool,
        pub categorical: bool,
    }
    defaults {
        variant: super::variant::HeatmapVariant::Basic,
        row_labels: &[],
        col_labels: &[],
        flat_matrix: &[],
        show_values: true,
        value_min_cell: 26,
        value_decimals: 2,
        col_label_angle: 40,
        color_low: 0x6366F1,
        color_mid: 0xfafbfc,
        color_high: 0xF43F5E,
        palette: &[],
        discrete_steps: 0,
        log_scale: false,
        diverging: false,
        x_widths: &[],
        y_heights: &[],
        annotate: false,
        categorical: false,
    }
);
