use serde::{Deserialize, Serialize};

#[derive(Clone, PartialEq, Serialize, Deserialize)]
pub(super) enum Layer {
    Bg,
    Fg,
}

impl Layer {
    pub(super) fn from_str(s: &str) -> Self {
        if s == "bg" {
            Layer::Bg
        } else {
            Layer::Fg
        }
    }
}

#[derive(Clone)]
pub(super) struct PlacedInfo {
    pub(super) x: f64,
    pub(super) y: f64,
    pub(super) w: f64,
    pub(super) h: f64,
    pub(super) native_w: f64,
    pub(super) native_h: f64,
    pub(super) rotation: f64,
    pub(super) element_idx: usize,
    pub(super) plot: Option<super::anchors::PlotFrame>,
}

#[derive(Clone, Serialize, Deserialize)]
pub(super) enum El {
    Chart {
        html: String,
        x: f64,
        y: f64,
        w: f64,
        h: f64,
        native_w: f64,
        native_h: f64,
        rotation: f64,
        opacity: f64,
        clip: String,
        group: String,
        name: String,
        ref_id: usize,
    },
    Image {
        src: String,
        x: f64,
        y: f64,
        w: f64,
        h: f64,
        rotation: f64,
        opacity: f64,
        clip: String,
        group: String,
        name: String,
    },
    Text {
        content: String,
        x: f64,
        y: f64,
        size: f64,
        color: String,
        opacity: f64,
        rotation: f64,
        anchor: String,
        weight: String,
        ls: f64,
        font: String,
        layer: Layer,
        name: String,
        group: String,
    },
    Line {
        x1: f64,
        y1: f64,
        x2: f64,
        y2: f64,
        color: String,
        width: f64,
        dash: String,
        opacity: f64,
        cap: String,
        layer: Layer,
        group: String,
        name: String,
    },
    Curve {
        pts: Vec<(f64, f64)>,
        color: String,
        width: f64,
        opacity: f64,
        tension: f64,
        fill: String,
        layer: Layer,
        name: String,
    },
    Connector {
        x1: f64,
        y1: f64,
        x2: f64,
        y2: f64,
        color: String,
        width: f64,
        opacity: f64,
        bend: f64,
        layer: Layer,
        name: String,
    },
    Circle {
        cx: f64,
        cy: f64,
        r: f64,
        fill: String,
        stroke: String,
        sw: f64,
        opacity: f64,
        layer: Layer,
        group: String,
        name: String,
    },
    Ring {
        cx: f64,
        cy: f64,
        r_inner: f64,
        r_outer: f64,
        fill: String,
        stroke: String,
        sw: f64,
        opacity: f64,
        layer: Layer,
        name: String,
    },
    Rect {
        x: f64,
        y: f64,
        w: f64,
        h: f64,
        fill: String,
        stroke: String,
        sw: f64,
        rx: f64,
        opacity: f64,
        rotation: f64,
        layer: Layer,
        name: String,
        group: String,
    },
    Polygon {
        pts: Vec<(f64, f64)>,
        fill: String,
        stroke: String,
        sw: f64,
        opacity: f64,
        layer: Layer,
        group: String,
        name: String,
    },
    RawPath {
        d: String,
        fill: String,
        stroke: String,
        sw: f64,
        opacity: f64,
        layer: Layer,
        name: String,
    },
    Arrow {
        x1: f64,
        y1: f64,
        x2: f64,
        y2: f64,
        color: String,
        width: f64,
        head_size: f64,
        opacity: f64,
        layer: Layer,
        name: String,
    },
    Annotate {
        text: String,
        ax: f64,
        ay: f64,
        tx: f64,
        ty: f64,
        color: String,
        size: f64,
        line_dash: String,
        lw: f64,
        bg: String,
        layer: Layer,
        name: String,
    },
    GradDef {
        id: String,
        from_color: String,
        to_color: String,
        x1: f64,
        y1: f64,
        x2: f64,
        y2: f64,
    },
    Arc {
        cx: f64,
        cy: f64,
        r: f64,
        start_deg: f64,
        end_deg: f64,
        color: String,
        width: f64,
        opacity: f64,
        cap: String,
        layer: Layer,
        name: String,
    },
    Wedge {
        cx: f64,
        cy: f64,
        r_inner: f64,
        r_outer: f64,
        start_deg: f64,
        end_deg: f64,
        fill: String,
        stroke: String,
        sw: f64,
        opacity: f64,
        layer: Layer,
        group: String,
        name: String,
    },
    Ribbon {
        cx: f64,
        cy: f64,
        r: f64,
        a_start: f64,
        a_end: f64,
        b_start: f64,
        b_end: f64,
        fill: String,
        opacity: f64,
        layer: Layer,
        name: String,
    },
    RadialGradDef {
        id: String,
        from_color: String,
        to_color: String,
        cx: f64,
        cy: f64,
        r: f64,
    },
}
