crate::declare_named_region_set! {
    (south_africa, "africa/south_africa_provinces", 865.88, 1000.00, "south_africa_provinces", &["south_africa", "za", "rsa", "south_african_provinces"], "South Africa (provinces)", &[]),
    (egypt, "africa/egypt_governorates", 1000.00, 791.27, "egypt_governorates", &["egypt", "eg", "egyptian_governorates"], "Egypt (governorates)", &[]),
    (nigeria, "africa/nigeria_states", 1000.00, 800.75, "nigeria_states", &["nigeria", "ng", "nigerian_states"], "Nigeria (states)", &[]),
    (morocco, "africa/morocco_regions", 1000.00, 907.69, "morocco_regions", &["morocco", "ma", "maroc", "moroccan_regions"], "Morocco (regions)", &[]),
    (kenya, "africa/kenya_counties", 823.51, 1000.00, "kenya_counties", &["kenya", "ke", "kenyan_counties"], "Kenya (counties)", &[]),
    (algeria, "africa/algeria_provinces", 1000.00, 877.35, "algeria_provinces", &["algeria", "dz", "algerie", "algerian_provinces"], "Algeria (provinces)", &[]),
    (tunisia, "africa/tunisia_governorates", 573.94, 1000.00, "tunisia_governorates", &["tunisia", "tn", "tunisie", "tunisian_governorates"], "Tunisia (governorates)", &[]),
    (libya, "africa/libya_districts", 1000.00, 862.34, "libya_districts", &["libya", "ly", "libyan_districts"], "Libya (districts)", &[]),
    (sudan, "africa/sudan_states", 1000.00, 806.54, "sudan_states", &["sudan", "sd", "sudanese_states"], "Sudan (states)", &[]),
    (ghana, "africa/ghana_regions", 692.59, 1000.00, "ghana_regions", &["ghana", "gh", "ghanaian_regions"], "Ghana (regions)", &[]),
    (senegal, "africa/senegal_regions", 1000.00, 712.18, "senegal_regions", &["senegal", "sn", "senegalese_regions"], "Senegal (regions)", &[]),
    (zambia, "africa/zambia_provinces", 1000.00, 844.44, "zambia_provinces", &["zambia", "zm", "zambian_provinces"], "Zambia (provinces)", &[]),
    (zimbabwe, "africa/zimbabwe_provinces", 1000.00, 866.95, "zimbabwe_provinces", &["zimbabwe", "zw", "zimbabwean_provinces"], "Zimbabwe (provinces)", &[]),
    (angola, "africa/angola_provinces", 908.51, 1000.00, "angola_provinces", &["angola", "ao", "angolan_provinces"], "Angola (provinces)", &[]),
    (dr_congo, "africa/dr_congo_provinces", 1000.00, 987.61, "dr_congo_provinces", &["dr_congo", "cd", "drc", "democratic_republic_of_congo", "congo_kinshasa"], "DR Congo (provinces)", &[]),
    (cameroon, "africa/cameroon_regions", 674.10, 1000.00, "cameroon_regions", &["cameroon", "cm", "cameroun", "cameroonian_regions"], "Cameroon (regions)", &[]),
    (mali, "africa/mali_regions", 1000.00, 900.32, "mali_regions", &["mali", "ml", "malian_regions"], "Mali (regions)", &[]),
    (niger, "africa/niger_regions", 1000.00, 747.38, "niger_regions", &["niger", "ne", "nigerien_regions"], "Niger (regions)", &[]),
    (tanzania, "africa/tanzania_regions", 1000.00, 965.59, "tanzania_regions", &["tanzania", "tz", "tanzanian_regions"], "Tanzania (regions)", &[]),
    (ethiopia, "africa/ethiopia_regions", 1000.00, 765.62, "ethiopia_regions", &["ethiopia", "et", "ethiopian_regions"], "Ethiopia (regions)", &[]),
    (namibia, "africa/namibia_regions", 1000.00, 886.74, "namibia_regions", &["namibia", "na", "namibian_regions"], "Namibia (regions)", &[]),
    (botswana, "africa/botswana_districts", 1000.00, 972.07, "botswana_districts", &["botswana", "bw", "botswanan_districts"], "Botswana (districts)", &[]),
    (mozambique, "africa/mozambique_provinces", 648.77, 1000.00, "mozambique_provinces", &["mozambique", "mz", "mozambican_provinces"], "Mozambique (provinces)", &[]),
    (uganda, "africa/uganda_districts", 958.40, 1000.00, "uganda_districts", &["uganda", "ug", "ugandan_districts"], "Uganda (districts)", &[]),
    (rwanda, "africa/rwanda_provinces", 1000.00, 870.77, "rwanda_provinces", &["rwanda", "rw", "rwandan_provinces"], "Rwanda (provinces)", &[]),
    (burkina_faso, "africa/burkina_faso_provinces", 1000.00, 718.84, "burkina_faso_provinces", &["burkina_faso", "bf", "burkinabe_provinces"], "Burkina Faso (provinces)", &[]),
    (ivory_coast, "africa/ivory_coast_departments", 865.21, 1000.00, "ivory_coast_departments", &["ivory_coast", "ci", "cote_divoire", "ivorian_departments"], "Ivory Coast (departments)", &[]),
    (guinea, "africa/guinea_prefectures", 1000.00, 739.10, "guinea_prefectures", &["guinea", "gn", "guinean_prefectures"], "Guinea (prefectures)", &[]),
    (sierra_leone, "africa/sierra_leone_provinces", 981.24, 1000.00, "sierra_leone_provinces", &["sierra_leone", "sl", "sierra_leonean_provinces"], "Sierra Leone (provinces)", &[]),
    (liberia, "africa/liberia_counties", 970.11, 1000.00, "liberia_counties", &["liberia", "lr", "liberian_counties"], "Liberia (counties)", &[]),
    (chad, "africa/chad_prefectures", 658.90, 1000.00, "chad_prefectures", &["chad", "td", "chadian_prefectures"], "Chad (prefectures)", &[]),
    (somalia, "africa/somalia_regions", 763.71, 1000.00, "somalia_regions", &["somalia", "so", "somali_regions"], "Somalia (regions)", &[]),
    (eritrea, "africa/eritrea_regions", 1000.00, 842.48, "eritrea_regions", &["eritrea", "er", "eritrean_regions"], "Eritrea (regions)", &[]),
    (djibouti, "africa/djibouti_regions", 938.99, 1000.00, "djibouti_regions", &["djibouti", "dj", "djiboutian_regions"], "Djibouti (regions)", &[]),
    (benin, "africa/benin_departments", 497.55, 1000.00, "benin_departments", &["benin", "bj", "beninese_departments"], "Benin (departments)", &[]),
    (togo, "africa/togo_regions", 387.02, 1000.00, "togo_regions", &["togo", "tg", "togolese_regions"], "Togo (regions)", &[]),
    (gabon, "africa/gabon_provinces", 927.16, 1000.00, "gabon_provinces", &["gabon", "ga", "gabonese_provinces"], "Gabon (provinces)", &[]),
    (central_african_republic, "africa/car_prefectures", 1000.00, 671.39, "car_prefectures", &["central_african_republic", "cf", "car", "centrafrique"], "Central African Republic (prefectures)", &[]),
    (malawi, "africa/malawi_districts", 417.97, 1000.00, "malawi_districts", &["malawi", "mw", "malawian_districts"], "Malawi (districts)", &[]),
    (lesotho, "africa/lesotho_districts", 1000.00, 857.95, "lesotho_districts", &["lesotho", "ls", "basotho_districts"], "Lesotho (districts)", &[]),
    (eswatini, "africa/eswatini_districts", 844.47, 1000.00, "eswatini_districts", &["eswatini", "sz", "swaziland", "swazi_districts"], "Eswatini (districts)", &[]),
    (mauritania, "africa/mauritania_regions", 976.78, 1000.00, "mauritania_regions", &["mauritania", "mr", "mauritanian_regions"], "Mauritania (regions)", &[]),
    (gambia, "africa/gambia_divisions", 1000.00, 250.74, "gambia_divisions", &["gambia", "gm", "gambian_divisions"], "Gambia (divisions)", &[]),
    (republic_of_congo, "africa/republic_of_congo_regions", 862.57, 1000.00, "republic_of_congo_regions", &["republic_of_congo", "cg", "congo_brazzaville", "congo"], "Republic of the Congo (regions)", &[]),
    (guinea_bissau, "africa/guinea_bissau_regions", 1000.00, 571.04, "guinea_bissau_regions", &["guinea_bissau", "gw", "guinea_bissauan_regions"], "Guinea-Bissau (regions)", &[]),
    (sao_tome_and_principe, "africa/sao_tome_and_principe_regions", 597.41, 1000.00, "sao_tome_and_principe_regions", &["sao_tome_and_principe", "st", "sao_tome"], "Sao Tome and Principe (regions)", &[]),
    (cape_verde, "africa/cape_verde_islands", 1000.00, 888.19, "cape_verde_islands", &["cape_verde", "cv", "cabo_verde", "cape_verdean_islands"], "Cape Verde (islands)", &[]),
    (burundi, "africa/burundi_provinces", 855.01, 1000.00, "burundi_provinces", &["burundi", "bi", "burundian_provinces"], "Burundi (provinces)", &[]),
    (comoros, "africa/comoros_islands", 1000.00, 774.45, "comoros_islands", &["comoros", "km", "comorian_islands"], "Comoros (islands)", &[]),
    (equatorial_guinea, "africa/equatorial_guinea_provinces", 1000.00, 916.80, "equatorial_guinea_provinces", &["equatorial_guinea", "gq", "equatoguinean_provinces"], "Equatorial Guinea (provinces)", &[]),
    (madagascar, "africa/madagascar_regions", 533.21, 1000.00, "madagascar_regions", &["madagascar", "mg", "malagasy_regions"], "Madagascar (regions)", &[]),
    (mauritius, "africa/mauritius_districts", 915.13, 1000.00, "mauritius_districts", &["mauritius", "mu", "mauritian_districts"], "Mauritius (districts)", &[]),
    (south_sudan, "africa/south_sudan_states", 1000.00, 739.53, "south_sudan_states", &["south_sudan", "ss", "south_sudanese_states"], "South Sudan (states)", &[]),
    (seychelles, "africa/seychelles_districts", 719.59, 1000.00, "seychelles_districts", &["seychelles", "sc", "seychellois_districts"], "Seychelles (districts)", &[]),
}
