crate::declare_named_region_set! {
    (india, "asia/india_states", 1000.00, 983.95, "india_states", &["india", "in", "bharat", "indian_states"], "India (states & union territories)", &[]),
    (japan, "asia/japan_prefectures", 1000.00, 686.31, "japan_prefectures", &["japan", "jp", "nihon", "nippon", "japanese_prefectures"], "Japan (prefectures)", &[]),
    (china, "asia/china_provinces", 1000.00, 617.85, "china_provinces", &["china", "cn", "zhongguo", "chinese_provinces", "prc"], "China (provinces)", &[]),
    (indonesia, "asia/indonesia_provinces", 1000.00, 366.21, "indonesia_provinces", &["indonesia", "id", "indonesian_provinces"], "Indonesia (provinces)", &[]),
    (south_korea, "asia/south_korea_provinces", 1000.00, 860.43, "south_korea_provinces", &["south_korea", "kr", "korea", "korean_provinces"], "South Korea (provinces)", &[]),
    (vietnam, "asia/vietnam_provinces", 496.85, 1000.00, "vietnam_provinces", &["vietnam", "vn", "viet_nam", "vietnamese_provinces"], "Vietnam (provinces)", &[]),
    (thailand, "asia/thailand_provinces", 560.21, 1000.00, "thailand_provinces", &["thailand", "th", "siam", "thai_provinces"], "Thailand (provinces)", &[]),
    (philippines, "asia/philippines_provinces", 586.81, 1000.00, "philippines_provinces", &["philippines", "ph", "filipino_provinces"], "Philippines (provinces)", &[]),
    (pakistan, "asia/pakistan_provinces", 1000.00, 824.46, "pakistan_provinces", &["pakistan", "pk", "pakistani_provinces"], "Pakistan (provinces)", &[]),
    (bangladesh, "asia/bangladesh_divisions", 785.25, 1000.00, "bangladesh_divisions", &["bangladesh", "bd", "bangladeshi_divisions"], "Bangladesh (divisions)", &[]),
    (turkey, "asia/turkey_provinces", 1000.00, 327.99, "turkey_provinces", &["turkey", "tr", "turkiye", "turkish_provinces"], "Turkey (provinces)", &[]),
    (saudi_arabia, "asia/saudi_arabia_provinces", 1000.00, 747.71, "saudi_arabia_provinces", &["saudi_arabia", "sa", "ksa", "saudi_provinces"], "Saudi Arabia (provinces)", &[]),
    (israel, "asia/israel_districts", 418.61, 1000.00, "israel_districts", &["israel", "il", "yisrael", "israeli_districts"], "Israel (districts)", &[]),
    (jordan, "asia/jordan_governorates", 1000.00, 962.95, "jordan_governorates", &["jordan", "jo", "urdun", "jordanian_governorates"], "Jordan (governorates)", &[]),
    (lebanon, "asia/lebanon_governorates", 921.88, 1000.00, "lebanon_governorates", &["lebanon", "lb", "lubnan", "lebanese_governorates"], "Lebanon (governorates)", &[]),
    (syria, "asia/syria_governorates", 1000.00, 753.23, "syria_governorates", &["syria", "sy", "suriya", "syrian_governorates"], "Syria (governorates)", &[]),
    (iraq, "asia/iraq_governorates", 1000.00, 849.52, "iraq_governorates", &["iraq", "iq", "al_iraq", "iraqi_governorates"], "Iraq (governorates)", &[]),
    (yemen, "asia/yemen_governorates", 1000.00, 573.94, "yemen_governorates", &["yemen", "ye", "al_yaman", "yemeni_governorates"], "Yemen (governorates)", &[]),
    (oman, "asia/oman_governorates", 807.30, 1000.00, "oman_governorates", &["oman", "om", "uman", "omani_governorates"], "Oman (governorates)", &[]),
    (uae, "asia/uae_emirates", 1000.00, 717.42, "uae_emirates", &["uae", "ae", "united_arab_emirates", "emirates"], "United Arab Emirates (emirates)", &[]),
    (qatar, "asia/qatar_municipalities", 540.90, 1000.00, "qatar_municipalities", &["qatar", "qa", "qatari_municipalities"], "Qatar (municipalities)", &[]),
    (kuwait, "asia/kuwait_governorates", 1000.00, 823.38, "kuwait_governorates", &["kuwait", "kw", "al_kuwayt", "kuwaiti_governorates"], "Kuwait (governorates)", &[]),
    (afghanistan, "asia/afghanistan_provinces", 1000.00, 630.80, "afghanistan_provinces", &["afghanistan", "af", "afghan_provinces"], "Afghanistan (provinces)", &[]),
    (nepal, "asia/nepal_provinces", 1000.00, 500.46, "nepal_provinces", &["nepal", "np", "nepali_provinces"], "Nepal (provinces)", &[]),
    (sri_lanka, "asia/sri_lanka_provinces", 572.10, 1000.00, "sri_lanka_provinces", &["sri_lanka", "lk", "ceylon", "sri_lankan_provinces"], "Sri Lanka (provinces)", &[]),
    (myanmar, "asia/myanmar_regions", 480.00, 1000.00, "myanmar_regions", &["myanmar", "mm", "burma", "myanmar_states"], "Myanmar (states & regions)", &[]),
    (cambodia, "asia/cambodia_provinces", 1000.00, 809.65, "cambodia_provinces", &["cambodia", "kh", "kampuchea", "cambodian_provinces"], "Cambodia (provinces)", &[]),
    (laos, "asia/laos_provinces", 881.91, 1000.00, "laos_provinces", &["laos", "la", "lao", "laotian_provinces"], "Laos (provinces)", &[]),
    (malaysia, "asia/malaysia_states", 1000.00, 331.30, "malaysia_states", &["malaysia", "my", "malaysian_states"], "Malaysia (states)", &[]),
    (singapore, "asia/singapore_districts", 1000.00, 507.73, "singapore_districts", &["singapore", "sg", "singaporean_districts"], "Singapore (districts)", &[]),
    (mongolia, "asia/mongolia_provinces", 1000.00, 327.73, "mongolia_provinces", &["mongolia", "mn", "mongolian_provinces"], "Mongolia (provinces)", &[]),
    (taiwan, "asia/taiwan_counties", 1000.00, 907.94, "taiwan_counties", &["taiwan", "tw", "formosa", "taiwanese_counties"], "Taiwan (counties)", &[]),
    (uzbekistan, "asia/uzbekistan_regions", 1000.00, 487.61, "uzbekistan_regions", &["uzbekistan", "uz", "uzbek_regions"], "Uzbekistan (regions)", &[]),
    (kazakhstan, "asia/kazakhstan_regions", 1000.00, 363.56, "kazakhstan_regions", &["kazakhstan", "kz", "kazakh_regions"], "Kazakhstan (regions)", &[]),
    (azerbaijan, "asia/azerbaijan_districts", 1000.00, 597.79, "azerbaijan_districts", &["azerbaijan", "az", "azerbaijani_districts"], "Azerbaijan (districts)", &[]),
    (armenia, "asia/armenia_provinces", 1000.00, 766.43, "armenia_provinces", &["armenia", "am", "hayastan", "armenian_provinces"], "Armenia (provinces)", &[]),
    (georgia_country, "asia/georgia_regions", 1000.00, 377.37, "georgia_regions", &["georgia", "ge", "sakartvelo", "georgian_regions"], "Georgia (regions)", &[]),
    (iran, "asia/iran_provinces", 1000.00, 762.10, "iran_provinces", &["iran", "ir", "persia", "iranian_provinces"], "Iran (provinces)", &[]),
    (north_korea, "asia/north_korea_provinces", 1000.00, 822.15, "north_korea_provinces", &["north_korea", "kp", "dprk", "north_korean_provinces"], "North Korea (provinces)", &[]),
    (bhutan, "asia/bhutan_districts", 1000.00, 494.91, "bhutan_districts", &["bhutan", "bt", "bhutanese_districts"], "Bhutan (districts)", &[]),
    (maldives, "asia/maldives_atolls", 137.04, 1000.00, "maldives_atolls", &["maldives", "mv", "maldivian_atolls"], "Maldives (atolls)", &[]),
    (brunei, "asia/brunei_districts", 1000.00, 763.99, "brunei_districts", &["brunei", "bn", "bruneian_districts"], "Brunei (districts)", &[]),
    (timor_leste, "asia/timor_leste_districts", 1000.00, 416.12, "timor_leste_districts", &["timor_leste", "tl", "east_timor", "east_timorese_districts"], "Timor-Leste (districts)", &[]),
    (bahrain, "asia/bahrain_governorates", 620.94, 1000.00, "bahrain_governorates", &["bahrain", "bh", "bahraini_governorates"], "Bahrain (governorates)", &[]),
    (kyrgyzstan, "asia/kyrgyzstan_regions", 1000.00, 369.17, "kyrgyzstan_regions", &["kyrgyzstan", "kg", "kyrgyz_regions"], "Kyrgyzstan (regions)", &[]),
    (tajikistan, "asia/tajikistan_regions", 1000.00, 557.61, "tajikistan_regions", &["tajikistan", "tj", "tajik_regions"], "Tajikistan (regions)", &[]),
    (turkmenistan, "asia/turkmenistan_provinces", 1000.00, 538.46, "turkmenistan_provinces", &["turkmenistan", "tm", "turkmen_provinces"], "Turkmenistan (provinces)", &[]),
}
