crate::declare_named_region_set! {
    (france, "europe/france_regions", 1000.00, 661.68, "france_regions", &["france", "fr", "francaise", "régions_françaises", "regions_francaises"], "France (régions)", &[]),
    (spain, "europe/spain_provinces", 1000.00, 717.69, "spain_provinces", &["spain", "es", "espana", "españa", "spanish_provinces"], "Spain (provinces)", &[]),
    (italy, "europe/italy_provinces", 1000.00, 973.25, "italy_provinces", &["italy", "it", "italia", "italian_provinces"], "Italy (provinces)", &[]),
    (poland, "europe/poland_voivodeships", 1000.00, 583.31, "poland_voivodeships", &["poland", "pl", "polska", "voivodeships", "wojewodztwa"], "Poland (voivodeships)", &[]),
    (netherlands, "europe/netherlands_provinces", 1000.00, 730.18, "netherlands_provinces", &["netherlands", "nl", "holland", "nederland", "dutch_provinces"], "Netherlands (provinces)", &[]),
    (sweden, "europe/sweden_counties", 953.38, 1000.00, "sweden_counties", &["sweden", "se", "sverige", "swedish_counties"], "Sweden (counties)", &[]),
    (russia, "europe/russia_regions", 1000.00, 112.96, "russia_regions", &["russia", "ru", "rossiya", "russian_regions"], "Russia (federal subjects)", &[]),
    (switzerland, "europe/switzerland_cantons", 1000.00, 438.95, "switzerland_cantons", &["switzerland", "ch", "suisse", "swiss_cantons"], "Switzerland (cantons)", &[]),
    (austria, "europe/austria_states", 1000.00, 344.97, "austria_states", &["austria", "at", "osterreich", "austrian_states"], "Austria (states)", &[]),
    (belgium, "europe/belgium_provinces", 1000.00, 519.38, "belgium_provinces", &["belgium", "be", "belgique", "belgian_provinces"], "Belgium (provinces)", &[]),
    (portugal, "europe/portugal_districts", 634.48, 1000.00, "portugal_districts", &["portugal", "pt", "portuguese_districts"], "Portugal (districts)", &[]),
    (greece, "europe/greece_regions", 1000.00, 805.21, "greece_regions", &["greece", "gr", "hellas", "greek_regions"], "Greece (regions)", &[]),
    (norway, "europe/norway_counties", 1000.00, 328.09, "norway_counties", &["norway", "no", "norge", "norwegian_counties"], "Norway (counties)", &[]),
    (finland, "europe/finland_regions", 1000.00, 937.67, "finland_regions", &["finland", "fi", "suomi", "finnish_regions"], "Finland (regions)", &[]),
    (denmark, "europe/denmark_regions", 1000.00, 450.96, "denmark_regions", &["denmark", "dk", "danmark", "danish_regions"], "Denmark (regions)", &[]),
    (ireland, "europe/ireland_counties", 1000.00, 878.70, "ireland_counties", &["ireland", "ie", "eire", "irish_counties"], "Ireland (counties)", &[]),
    (iceland, "europe/iceland_regions", 1000.00, 286.98, "iceland_regions", &["iceland", "is", "island", "icelandic_regions"], "Iceland (regions)", &[]),
    (slovakia, "europe/slovakia_regions", 1000.00, 325.15, "slovakia_regions", &["slovakia", "sk", "slovensko", "slovak_regions"], "Slovakia (regions)", &[]),
    (hungary, "europe/hungary_counties", 1000.00, 416.87, "hungary_counties", &["hungary", "hu", "magyarorszag", "hungarian_counties"], "Hungary (counties)", &[]),
    (romania, "europe/romania_counties", 1000.00, 489.05, "romania_counties", &["romania", "ro", "romanian_counties"], "Romania (counties)", &[]),
    (bulgaria, "europe/bulgaria_provinces", 1000.00, 477.80, "bulgaria_provinces", &["bulgaria", "bg", "bulgarian_provinces"], "Bulgaria (provinces)", &[]),
    (croatia, "europe/croatia_counties", 1000.00, 699.36, "croatia_counties", &["croatia", "hr", "hrvatska", "croatian_counties"], "Croatia (counties)", &[]),
    (bosnia, "europe/bosnia_cantons", 1000.00, 698.29, "bosnia_cantons", &["bosnia", "ba", "bosnia_and_herzegovina", "bosnian_cantons"], "Bosnia and Herzegovina (cantons)", &[]),
    (albania, "europe/albania_counties", 584.75, 1000.00, "albania_counties", &["albania", "al", "shqiperia", "albanian_counties"], "Albania (counties)", &[]),
    (lithuania, "europe/lithuania_counties", 1000.00, 434.94, "lithuania_counties", &["lithuania", "lt", "lietuva", "lithuanian_counties"], "Lithuania (counties)", &[]),
    (latvia, "europe/latvia_municipalities", 1000.00, 332.22, "latvia_municipalities", &["latvia", "lv", "latvija", "latvian_municipalities"], "Latvia (municipalities)", &[]),
    (estonia, "europe/estonia_counties", 1000.00, 339.16, "estonia_counties", &["estonia", "ee", "eesti", "estonian_counties"], "Estonia (counties)", &[]),
    (belarus, "europe/belarus_regions", 1000.00, 515.15, "belarus_regions", &["belarus", "by", "belorussia", "belarusian_regions"], "Belarus (regions)", &[]),
    (moldova, "europe/moldova_districts", 1000.00, 860.71, "moldova_districts", &["moldova", "md", "moldovan_districts"], "Moldova (districts)", &[]),
    (cyprus, "europe/cyprus_districts", 1000.00, 314.32, "cyprus_districts", &["cyprus", "cy", "kypros", "cypriot_districts"], "Cyprus (districts)", &[]),
    (czechia, "europe/czech_regions", 1000.00, 367.10, "czech_regions", &["czechia", "cz", "czech_republic", "czech"], "Czech Republic (regions)", &[]),
    (macedonia, "europe/macedonia_regions", 1000.00, 468.93, "macedonia_regions", &["macedonia", "mk", "north_macedonia", "macedonian_regions"], "North Macedonia (municipalities)", &[]),
    (serbia, "europe/serbia_districts", 1000.00, 951.53, "serbia_districts", &["serbia", "rs", "srbija", "serbian_districts"], "Serbia (districts)", &[]),
    (slovenia, "europe/slovenia_regions", 1000.00, 457.24, "slovenia_regions", &["slovenia", "si", "slovenija", "slovenian_municipalities"], "Slovenia (municipalities)", &[]),
    (ukraine, "europe/ukraine_oblasts", 1000.00, 396.93, "ukraine_oblasts", &["ukraine", "ua", "ukrainian_oblasts", "oblasts"], "Ukraine (oblasts)", &[]),
    (united_kingdom, "europe/united_kingdom_regions", 1000.00, 707.41, "united_kingdom_regions", &["united_kingdom", "uk", "gb", "great_britain", "britain", "england"], "United Kingdom (regions)", &[]),
    (andorra, "europe/andorra_parishes", 1000.00, 615.35, "andorra_parishes", &["andorra", "ad", "andorran_parishes"], "Andorra (parishes)", &[]),
    (liechtenstein, "europe/liechtenstein_communes", 664.62, 1000.00, "liechtenstein_communes", &["liechtenstein", "li", "liechtenstein_communes"], "Liechtenstein (communes)", &[]),
    (san_marino, "europe/san_marino_municipalities", 1000.00, 847.77, "san_marino_municipalities", &["san_marino", "sm", "san_marino_municipalities"], "San Marino (municipalities)", &[]),
    (malta, "europe/malta_councils", 1000.00, 715.36, "malta_councils", &["malta", "mt", "maltese_councils", "local_councils"], "Malta (local councils)", &[]),
    (luxembourg, "europe/luxembourg_districts", 1000.00, 931.44, "luxembourg_districts", &["luxembourg", "lu", "luxembourgish_districts"], "Luxembourg (districts)", &[]),
    (montenegro, "europe/montenegro_municipalities", 1000.00, 882.33, "montenegro_municipalities", &["montenegro", "me", "montenegrin_municipalities"], "Montenegro (municipalities)", &[]),
}
