crate::declare_named_region_set! {
    (mexico, "north-america/mexico_states", 1000.00, 573.65, "mexico_states", &["mexico", "mx", "mexico_estados", "mexican_states"], "Mexico (states)", &[]),
    (canada, "north-america/canada_provinces", 1000.00, 468.92, "canada_provinces", &["canada", "ca", "canadian_provinces", "provinces"], "Canada (provinces & territories)", &[]),
    (panama, "north-america/panama_provinces", 1000.00, 411.47, "panama_provinces", &["panama", "pa", "panamanian_provinces"], "Panama (provinces)", &[]),
    (costa_rica, "north-america/costa_rica_provinces", 799.81, 1000.00, "costa_rica_provinces", &["costa_rica", "cr", "costa_rican_provinces"], "Costa Rica (provinces)", &[]),
    (nicaragua, "north-america/nicaragua_departments", 1000.00, 870.44, "nicaragua_departments", &["nicaragua", "ni", "nicaraguan_departments"], "Nicaragua (departments)", &[]),
    (honduras, "north-america/honduras_departments", 1000.00, 712.12, "honduras_departments", &["honduras", "hn", "honduran_departments"], "Honduras (departments)", &[]),
    (el_salvador, "north-america/el_salvador_departments", 1000.00, 531.36, "el_salvador_departments", &["el_salvador", "sv", "salvadoran_departments"], "El Salvador (departments)", &[]),
    (guatemala, "north-america/guatemala_departments", 985.48, 1000.00, "guatemala_departments", &["guatemala", "gt", "guatemalan_departments"], "Guatemala (departments)", &[]),
    (cuba, "north-america/cuba_provinces", 1000.00, 317.82, "cuba_provinces", &["cuba", "cu", "cuban_provinces"], "Cuba (provinces)", &[]),
    (dominican_republic, "north-america/dominican_republic_provinces", 1000.00, 649.82, "dominican_republic_provinces", &["dominican_republic", "do", "republica_dominicana"], "Dominican Republic (provinces)", &[]),
    (jamaica, "north-america/jamaica_parishes", 1000.00, 375.87, "jamaica_parishes", &["jamaica", "jm", "jamaican_parishes"], "Jamaica (parishes)", &[]),
    (haiti, "north-america/haiti_departments", 1000.00, 724.14, "haiti_departments", &["haiti", "ht", "haitian_departments"], "Haiti (departments)", &[]),
    (belize, "north-america/belize_districts", 556.64, 1000.00, "belize_districts", &["belize", "bz", "belizean_districts"], "Belize (districts)", &[]),
    (trinidad_and_tobago, "north-america/trinidad_and_tobago_regions", 1000.00, 930.60, "trinidad_and_tobago_regions", &["trinidad_and_tobago", "tt", "trinidad", "tobago"], "Trinidad and Tobago (regions)", &[]),
    (bahamas, "north-america/bahamas_districts", 1000.00, 878.48, "bahamas_districts", &["bahamas", "bs", "the_bahamas", "bahamian_districts"], "The Bahamas (districts)", &[]),
    (grenada, "north-america/grenada_parishes", 700.13, 1000.00, "grenada_parishes", &["grenada", "gd", "grenadian_parishes"], "Grenada (parishes)", &[]),
    (saint_lucia, "north-america/saint_lucia_quarters", 492.32, 1000.00, "saint_lucia_quarters", &["saint_lucia", "st_lucia", "lc", "saint_lucian_quarters"], "Saint Lucia (quarters)", &[]),
    (barbados, "north-america/barbados_parishes", 774.76, 1000.00, "barbados_parishes", &["barbados", "bb", "barbadian_parishes"], "Barbados (parishes)", &[]),
    (saint_vincent_and_the_grenadines, "north-america/saint_vincent_and_the_grenadines_parishes", 422.19, 1000.00, "saint_vincent_and_the_grenadines_parishes", &["saint_vincent_and_the_grenadines", "st_vincent", "vc", "saint_vincent"], "Saint Vincent and the Grenadines (parishes)", &[]),
    (antigua_and_barbuda, "north-america/antigua_and_barbuda_parishes", 855.41, 1000.00, "antigua_and_barbuda_parishes", &["antigua_and_barbuda", "ag", "antigua", "barbuda"], "Antigua and Barbuda (parishes)", &[]),
    (dominica, "north-america/dominica_parishes", 554.72, 1000.00, "dominica_parishes", &["dominica", "dm", "dominican_parishes"], "Dominica (parishes)", &[]),
    (saint_kitts_and_nevis, "north-america/saint_kitts_and_nevis_parishes", 1000.00, 972.27, "saint_kitts_and_nevis_parishes", &["saint_kitts_and_nevis", "st_kitts", "kn", "saint_kitts"], "Saint Kitts and Nevis (parishes)", &[]),
}
