crate::declare_named_region_set! {
    (australia, "oceania/australia_states", 1000.00, 985.35, "australia_states", &["australia", "au", "aussie", "australian_states"], "Australia (states & territories)", &[]),
    (new_zealand, "oceania/new_zealand_regions", 939.42, 1000.00, "new_zealand_regions", &["new_zealand", "nz", "aotearoa", "kiwi", "new_zealand_regions"], "New Zealand (regions)", &[]),
    (papua_new_guinea, "oceania/papua_new_guinea_provinces", 1000.00, 680.63, "papua_new_guinea_provinces", &["papua_new_guinea", "png", "papuan_provinces"], "Papua New Guinea (provinces)", &[]),
    (fiji, "oceania/fiji_divisions", 779.03, 1000.00, "fiji_divisions", &["fiji", "fj", "fijian_divisions"], "Fiji (divisions)", &[]),
    (solomon_islands, "oceania/solomon_islands_provinces", 1000.00, 427.30, "solomon_islands_provinces", &["solomon_islands", "sb", "solomon_islander_provinces"], "Solomon Islands (provinces)", &[]),
    (vanuatu, "oceania/vanuatu_provinces", 469.99, 1000.00, "vanuatu_provinces", &["vanuatu", "vu", "ni_vanuatu_provinces"], "Vanuatu (provinces)", &[]),
    (samoa, "oceania/samoa_districts", 1000.00, 438.70, "samoa_districts", &["samoa", "ws", "samoan_districts"], "Samoa (districts)", &[]),
    (tonga, "oceania/tonga_divisions", 369.37, 1000.00, "tonga_divisions", &["tonga", "to", "tongan_divisions"], "Tonga (divisions)", &[]),
    (micronesia, "oceania/micronesia_states", 1000.00, 354.54, "micronesia_states", &["micronesia", "fm", "fsm", "micronesian_states"], "Micronesia (states)", &[]),
    (palau, "oceania/palau_states", 698.63, 1000.00, "palau_states", &["palau", "pw", "palauan_states"], "Palau (states)", &[]),
    (marshall_islands, "oceania/marshall_islands_chains", 672.29, 1000.00, "marshall_islands_chains", &["marshall_islands", "mh", "marshallese_chains"], "Marshall Islands (chains)", &[]),
    (kiribati, "oceania/kiribati_regions", 1000.00, 418.23, "kiribati_regions", &["kiribati", "ki", "i_kiribati_regions"], "Kiribati (regions)", &[]),
    (nauru, "oceania/nauru_districts", 834.45, 1000.00, "nauru_districts", &["nauru", "nr", "nauruan_districts"], "Nauru (districts)", &[]),
}
