crate::chart_config!(WordCloudConfig, 900, 500;
    struct {
        pub variant: super::variant::WordCloudVariant,
        pub shape: super::shape::WordCloudShape,
        pub words: &'a [String],
        pub frequencies: &'a [f64],
        pub palette: &'a [u32],
        pub min_font: f64,
        pub max_font: f64,
        pub bg_color: Option<&'a str>,
        pub mask: &'a [i32],
        pub mask_width: i32,
        pub mask_height: i32,
        pub points_x: &'a [f64],
        pub points_y: &'a [f64],
        pub point_clusters: &'a [i32],
        pub cluster_labels: &'a [String],
        pub edges_i: &'a [i32],
        pub edges_j: &'a [i32],
        pub edges_w: &'a [f64],
    }
    defaults {
        variant: super::variant::WordCloudVariant::Basic,
        shape: super::shape::WordCloudShape::Rect,
        words: &[],
        frequencies: &[],
        palette: &[],
        min_font: 12.0,
        max_font: 72.0,
        bg_color: None,
        mask: &[],
        mask_width: 0,
        mask_height: 0,
        points_x: &[],
        points_y: &[],
        point_clusters: &[],
        cluster_labels: &[],
        edges_i: &[],
        edges_j: &[],
        edges_w: &[],
    }
);
