pub type BuilderFn = fn(&str) -> String;

pub fn dispatch(family: &str) -> Option<BuilderFn> {
    use crate::plot::statistical as st;
    Some(match family {
        "arc_diagram" => st::build_arc_diagram,
        "area" => st::build_area_chart,
        "bar" => st::build_bar,
        "boxplot" | "box" => st::build_boxplot,
        "bubble" => st::build_bubble,
        "bullet" => st::build_bullet,
        "candlestick" => st::build_candlestick,
        "chord" => st::build_chord,
        "circle_pack" => st::build_circle_pack,
        "correlogram" => st::build_correlogram,
        "dendrogram" => st::build_dendrogram,
        "donut" => st::build_donut_chart,
        "dumbbell" => st::build_dumbbell,
        "eventplot" => st::build_eventplot,
        "facet" | "facet_grid" | "facetgrid" | "small_multiples" => st::build_facet,
        "funnel" => st::build_funnel,
        "gantt" => st::build_gantt,
        "gauge" => st::build_gauge,
        "grouped_bar" => st::build_grouped_bar,
        "hive" => st::build_hive,
        "heatmap" => st::build_heatmap,
        "hexbin" => st::build_hexbin,
        "histogram" | "hist" => st::build_histogram,
        "icicle" => st::build_icicle,
        "joint" | "jointplot" | "bivariate" => st::build_joint,
        "kde" | "density" => st::build_kde_chart,
        "line" | "lineplot" => st::build_line,
        "lollipop" => st::build_lollipop_chart,
        "multiline" => st::build_multiline_chart,
        "orbita" => st::build_orbita,
        "parallel" => st::build_parallel,
        "parcats" => st::build_parcats,
        "pie" => st::build_pie,
        "plot_web" => st::build_plot_web,
        "pulse" => st::build_pulse,
        "radar" | "polar" => st::build_radar_chart,
        "ridgeline" => st::build_ridgeline_chart,
        "sankey" => st::build_sankey,
        "scatter" => st::build_scatter_chart,
        "scatterternary" => st::build_scatter_ternary,
        "slope" => st::build_slope,
        "splom" => st::build_splom,
        "stackplot" => st::build_stackplot,
        "stacked_bar" => st::build_stacked_bar,
        "sunburst" => st::build_sunburst,
        "treemap" => st::build_treemap,
        "venn" => st::build_venn,
        "violin" => st::build_violin,
        "waterfall" => st::build_waterfall,
        "wordcloud" => st::build_wordcloud,
        _ => return None,
    })
}

pub fn family_names() -> &'static [&'static str] {
    &[
        "arc_diagram", "area", "bar", "boxplot", "bubble", "bullet", "candlestick", "chord",
        "circle_pack", "correlogram", "dendrogram", "donut", "dumbbell", "eventplot", "facet",
        "funnel", "gantt", "gauge", "grouped_bar", "hive", "heatmap", "hexbin", "histogram",
        "icicle", "joint", "kde", "line", "lollipop", "multiline", "orbita", "parallel",
        "parcats", "pie", "plot_web", "pulse", "radar", "ridgeline", "sankey", "scatter",
        "scatterternary", "slope", "splom", "stackplot", "stacked_bar", "sunburst", "treemap",
        "venn", "violin", "waterfall", "wordcloud",
    ]
}
