use crate::html::hover::HoverSlot;

pub struct BarConfig<'a> {
    pub variant: super::variant::BarVariant,
    pub theme: crate::plot::statistical::theme::ChartTheme,

    pub title: &'a str,
    pub x_label: &'a str,
    pub y_label: &'a str,
    pub width: i32,
    pub height: i32,
    pub gridlines: bool,
    pub sort_order: &'a str,
    pub legend_position: &'a str,
    pub hover: &'a [HoverSlot],
    pub palette: &'a [u32],

    pub labels: &'a [String],
    pub values: &'a [f64],
    pub values2: &'a [f64],
    pub color_hex: u32,
    pub color_low: u32,
    pub color_high: u32,
    pub color_groups: &'a [String],

    pub error_low: &'a [f64],
    pub error_high: &'a [f64],
    pub overlay_line: &'a [f64],
    pub overlay_line_label: &'a str,

    pub category_labels: &'a [String],
    pub series: &'a [(String, Vec<f64>)],
    pub series2: &'a [(String, Vec<f64>)],
    pub base_variant: &'a str,

    pub offset_groups: &'a [String],
    pub widths: &'a [f64],
    pub super_categories: &'a [String],

    pub icon_size: i32,
    pub max_icons_per_column: i32,
    pub units_per_icon: f64,
    pub unit_description: &'a str,

    pub show_text: bool,
    pub corner_radius: i32,
    pub bar_gap: f64,
    pub bargroup_gap: f64,
    pub orientation: u8,
}

impl<'a> Default for BarConfig<'a> {
    fn default() -> Self {
        Self {
            variant: super::variant::BarVariant::Basic,
            theme: crate::plot::statistical::theme::ChartTheme::None,
            title: "",
            x_label: "",
            y_label: "",
            width: 900,
            height: 480,
            gridlines: false,
            sort_order: "none",
            legend_position: "right",
            hover: &[],
            palette: &[],
            labels: &[],
            values: &[],
            values2: &[],
            color_hex: 0,
            color_low: 0x636EFA,
            color_high: 0xF43F5E,
            color_groups: &[],
            error_low: &[],
            error_high: &[],
            overlay_line: &[],
            overlay_line_label: "",
            category_labels: &[],
            series: &[],
            series2: &[],
            base_variant: "multicategory",
            offset_groups: &[],
            widths: &[],
            super_categories: &[],
            icon_size: 24,
            max_icons_per_column: 10,
            units_per_icon: 1.0,
            unit_description: "",
            show_text: false,
            corner_radius: 0,
            bar_gap: 0.2,
            bargroup_gap: 0.1,
            orientation: b'v',
        }
    }
}
